### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by dgregorius** [eoineoineoin/glTF_Physics#16]
Hi guys,

I really like the idea of having an GLTF extension for rigid body dynamics. Some ideas that came up when I read the proposed document.

**I would suggest to define the collision primitives as:**

1) Sphere: Center and Radius
2) Capsule: Two Centers and Radius
3) Hull: Buffer Index (Vertices) and uniform Scale
4) Mesh: Buffer Index (Vertices and Topology) and non-uniform scale

All points are assumed to be in the local space of the associated body. For other shapes eg. cylinder and cone I would either something along the line as above. Or even just define them as a Hull with an optional Hint.

For joints I would suggest to **not** make them part of a node. Joints don't really have a transform, but maybe in a physics authoring tool. I don't think glTF_Physics is a tool representation and I would suggest a separate joint array and a joint object has two node indices and two local frames. This way joints can also be defined as initially separated.

I think otherwise this looks really good! 

-Dirk

**Comment by eoineoineoin** [comment]
Hey Dirk,

Thanks for the feedback! I _suspect_ I understand some of the motivation for those changes (our own native spheres/capsules would have a very similar representation) - I'm a little concerned about adding transform-like fields to the geometry objects; purely because they're associated with nodes, which have a variety of ways to compose transforms. Let's hop on a call and draw some diagrams during the week.

Eoin

**Comment by eoineoineoin** [comment]
Closing as "not planned" - there was unfortunately quite a lot of resistance to adding additional offsets/transforms to shapes. Though, if there was a desire to minimize the amount of nodes, a future extension could still add that ability to shapes (I would certainly add support for such an extension in our tools).
