### ISSUE TITLE
Disallow CollisionPrimitive non-uniform scale and animation relative to RigidBody

### ISSUE THREAD

**Issue by lyuma** [eoineoineoin/glTF_Physics#17]
To start with, I've been working with OMI on their physics extension, and I brought these issues up at the last meeting there. @aaronfranke suggested I bring these to your attention, since the same issues are present in the MSFT spec here.

My dream glTF extension for Physics would allow import the content into the engine of my choice, and having that state be directly compatible with my physics engine of choice.

There are some issues related to collision primitive transforms which will require that additional runtime work be done in many engines unless they be forbidden in this spec.

1. Needs a note about the handling of non-uniform scale, or non-uniform scale should be entirely disallowed, except possibly for box shapes.
Different engines may handle non-uniform scale of rigid bodies and collision primitives differently. For example, Unity will change the height or radius of a capsule collider to approximate the non-uniform scale, but it is only best effort.

Furthermore, because this spec permits colliders to be descendants multiple levels deep, it is possible to introduce skew/shear into a node by the combination of non-uniform scale and rotation. I would hope this is forbidden, but it would be good to clarify this.

My opinion is non-uniform scale in any ancestor of a rigidbody or collider should be explicitly forbidden, with a possible exception of the exact node containing specific collision primitives such as box where non-uniform scale could be well defined.

2. From the RigidBody spec:
> Implementations of this extension should ensure that collider transforms are always kept in sync with node transforms - for example animated node transforms should be applied to the physics engine (even for static colliders).

This is a problem, because it's dictating specific runtime behavior, namely that animating the positions of colliders will modify the physics body.

When combined with the fact that colliders can be arbitrary descendants of rigid bodies, it implies that some system will need to detect whether a particular node was animated and update all collision shapes of descendent nodes within the physics system every frame.

I would prefer if animating nodes between a physics body and any colliders be forbidden in the spec.

**RigidBody** (may be animated)
    - Intermediate (not animatable)
    -      - CapsuleCollider (not animatable)
    -      - **Mesh** (may be animated)
    - **OtherNodes** (may be animated)

**Comment by eoineoineoin** [comment]
I don't think these should be forbidden.

### Non-uniform scale

Non-uniform scale coupled with a rotation is a bit of a pain, I agree, but the physics engine is going to have to deal with this regardless. It can occur in any scene hierarchy and is not just an artifact of having "descendants multiple levels deep."

Further, because of scene composition functionality like glXF or USD, it's impossible to detect until runtime. A file that doesn't appear to have any nodes containing shear can have it introduced when a totally separate file introduces additional transforms. Even worse, extensions like glTF Interactivity will add turing-completeness-level difficulty in detecting it.

So, this can't reasonably be enforced. A physics engine is going to have to do it's best to handle it. If that requires raising a warning to the user, so be it, but it should not result in an out-of-spec glTF file.

### Animated scale

> I would prefer if animating nodes between a physics body and any colliders be forbidden in the spec.

Absolutely cannot happen.

>> Implementations of this extension should ensure that collider transforms are always kept in sync with node transforms - for example animated node transforms should be applied to the physics engine (even for static colliders).

> This is a problem, because it's dictating specific runtime behavior, namely that animating the positions of colliders will modify the physics body.

This text is in the spec precisely to prevent implementations from ignoring their obligations. Tools like glTF or Godot have 
a scene hierarchy and animation as a core construct. A scene hierarchy *allows* you to modify the transform of intermediate nodes. I agree, it's more integration work, but if physics data is going to live in the scene hierarchy, it's going to have to obey the rules of the scene hierarchy.

If a user is animating a node, they're expecting that node to be transformed. Every other type of object (meshes, cameras, lights, sounds, you-name-it) will be transformed -- why should physics get a free pass to ignore the user's request? This will only frustrate, confuse and annoy users - they can see all their meshes update, but for some reason, this invisible physics collider isn't updating. By forbidding animations you're essentially saying that because *you* can't be bothered to update the transforms, all glTF users should be forbidden from doing so, even if they're not using your physics engine. Why do you get to decide that their use-cases are invalid?

### Saving files

I'll note that (e.g.) Godot _does_ allow me to create a file with any combination of:

1. Animated colliders
2. Colliders with shear
3. Non-uniformly-scaled colliders

In the latter case, a warning is presented, but the rest are silent. In all cases, the simulation does _something_ and the tscn is valid, can be saved/loaded/played, etc.. Suppose we did put those restrictions in; what would you propose happens when a user makes these constructs and attempts to save the scene glTF? Would you:

1. Refuse to save it?
2. Save an invalid glTF file?
3. Modify the user's data so it _is_ valid?

I'd suggest that all of these options are bad. Maybe there's another option I haven't thought of?

**Comment by aaronfranke** [comment]
> if physics data is going to live in the scene hierarchy, it's going to have to obey the rules of the scene hierarchy.

This is completely disregarding the reality of physics engines. The whole point of physics engines is to define physical movement. It can't allow everything the scene hierarchy does, it must be a subset.

If you are allowing a static collider to move (either a MSFT collision primitive with no body, or an OMI static body or shape), what is the purpose of having a kinematic body? You have previously explained that "the defining characteristic of a 'kinematic' body describes one which will pass through static geometry".

Therefore, if both nodes have their movement animated and both nodes have shape children, what is the difference in the MSFT spec between a body with `isKinematic` set to true, and a node with no extensions? Both are defining movement that doesn't have their motion affected by any other bodies/colliders and will pass through everything.

> I'll note that (e.g.) Godot does allow me ... In the latter case, a warning is presented, but the rest are silent.

Thanks for checking that, I've made a PR to warn about the invalid case of shearing: https://github.com/godotengine/godot/pull/79364

> * Refuse to save it?
> * Save an invalid glTF file?
> * Modify the user's data so it is valid?

Out of these, 2 seems like the best option, but let me reword it. It would save some data that does not follow the spec and therefore is not guaranteed to work in all physics engines, and should show a warning during saving and/or validation.

If some implementation wants to implement a superset of the standard with support for unusual physics shapes, I don't see a reason to disallow making such assets - but it needs to be not a part of the spec that most implementations are required to handle in order to be compliant with the spec, otherwise most implementations won't be compliant.
