### ISSUE TITLE
Should a glTF scene be interacted with other glTF scenes?

### ISSUE THREAD

**Issue by takahirox** [eoineoineoin/glTF_Physics#2]
Thanks for working for Physics in glTF. I have read through the specification and thought it may be unclear whether a glTF scene be interacted with other glTF scenes.

For example, imagine that two glTF files having `MSFT_Physics` extension are imported into an application. There is a chance that they have different gravity parameters. And `collisionLayers/Mask` properties are for a scene that a node belongs to, they don't take into account how they are configured in other glTF files.

**Comment by eoineoineoin** [comment]
Hey Takahiro,

I think the answer is "it depends on the application's use-case" - in the same sense that two separate glTF assets may or may not render to the same viewport, I think the same applies to physics.

You _may_ for example, want to split up your data into multiple scenes so y2ou don't need to load all of it at once (think streaming scenarios for large worlds); in that case, it does make sense that the physics (+rendering) data gets loaded into the same "simulation world" so that objects can interact across those scene boundaries.

However, there are scenarios where that isn't desirable. One reasonably common use-case we see this in is local simulation. Consider -say- a game where a character in a city can enter buildings, which are authored as different scenes. Both the city and each building interior is modelled around (0,0,0) - this would allow you to move the buildings in the city scene, without having to update the scenes for the interiors. Now, the interiors of all these scenes overlap mathematically, but the scenes really represent different conceptual coordinate systems. In this case, it makes sense to use a different "simulation world" for the city and each building interior.

Because of these different use-cases, I feel we shouldn't mandate any details about how multiple scenes should interact.

Our intention with the gravity was to give the glTF loader some indication of the scale and orientation of a scene, so that you could get some kind of reasonable behaviour if you were to load up a random asset that you downloaded from the Internet. However, in the case where you load two assets with different gravities into the same "simulation world," I agree that the result would _probably_ not be what was intended (although, there are interesting and useful effects you can get by doing that.)

I'd probably be inclined to say that the gravity used by the simulation should be defined by the application so that there's consistent behaviour - it's unlikely you'd want to load assets modelled with different scales/UP-axes into the same application, anyway. In that case, I'd err on the side of removing gravity from the specification.

In terms of the collision filtering, though, I'm not sure that there is a conflict? The specified masking should work regardless, with the exception that if you're pulling assets from different sources, the values for the filter may be used inconsistently. When we did filtering for USD [1], instead of a bitfield, we use an array of [arbitrary] string identifiers, which is less likely to be inconsistent, as content authors can choose strings to represent the conceptual "categories" an object belongs to. This _does_ hoist some complexity onto the "physics loading" code, but given the choice between "making one programmer's life slightly harder" and "making 1000's of artist's lives slightly harder," I'd choose the former. Would you agree? 

[1] https://graphics.pixar.com/usd/release/api/usd_physics_page_front.html#usdPhysics_collision_filtering
