### ISSUE TITLE
Rename KHR extensions to follow suggested Khronos naming convention

### ISSUE THREAD

**Issue by antpb** [eoineoineoin/glTF_Physics#23]
Hello! I noticed in this spec there were KHR extensions and wanted to create an issue to bring attention to the current naming being somewhat confusing when considering the naming conventions suggested by Khronos. 

https://github.com/KhronosGroup/glTF/tree/main/extensions#naming

I think the current proposed extensions in this repo would benefit from being named KHR_physics_body and KHR_physics_shape to follow the KHR_scope_action naming convention. This conversation came up in a recent OMI glTF extensions meeting and it was generally agreed to need alignment with KHR suggestions. 

> Names SHOULD be structured as `<PREFIX>_<scope>_<feature>`, where scope is an existing glTF concept (e.g. mesh, texture, image) and feature describes the functionality being added within that scope. This structure is recommended, but not required.

If not renamed to scope_action I think at minimum the `KHR_collision_shapes` and `KHR_rigid_bodies` extensions should not be plural to follow the requirement:

> Scope SHOULD be singular (e.g. mesh, texture), except where this would be inconsistent with an existing Khronos extension (e.g. materials, lights).

**Comment by eoineoineoin** [comment]
While I have no doubt that naming of all properties will be scrutinized as we go through the ratification process, the current name is a result of a discussion held in the Khronos 3D Formats Working Group on the 16th of last month.  The decision was that for existing extensions, the scope refers to extending existing objects. There was a strong preference to have a shorter name rather than trying to add prefixes referencing a top-level collection which wasn't there.

**Comment by aaronfranke** [comment]
> There was a strong preference to have a shorter name

`KHR_physics_shape` is 3 characters shorter than `KHR_collision_shapes`, so if there is a preference for shorter names, that name is shorter. The other two are the same length.

**Comment by sipkode** [comment]
KHR_rigid_bodies does seem to be a break from the Khronos recommendation, however.  What about something like `KHR_physics_rigidbody`?  It's longer, but more descriptive and fits the template.

**Comment by aaronfranke** [comment]
> The decision was that for existing extensions, the scope refers to extending existing objects.

That is not always true in existing extensions. The `lights` scope found in `KHR_lights_punctual`, `EXT_lights_ies`, and `EXT_lights_image_based` do not extend any existing glTF object. Aside from looking at precedent, I completely disagree that scope should only be for existing glTF objects, we should be able to make new scopes. I would like to be able to use `KHR_audio_*` and `KHR_physics_*` prefixes for naming audio and physics extensions.

> While KHR_collision_shapes does describe shapes whose purpose is not limited to physics.

I don't understand, isn't physics collision a subset of physics? Collision happens in physics engines. "Collision" seems more limiting than physics, not less. Or, at least, it only makes sense for us to define collision in the context of physics, because it otherwise has many meanings: a hash collision is completely unrelated to box shapes.

> KHR_rigid_bodies describes rigid bodies. It does not describe the more general concept of a physics body.

All of the physics described by this extension is rigid (in the physics sense), but that is assumed to be the default type of physics, so I disagree that physics isn't specific enough. Every physics engine assumes unsquishable by default.

But technically, do you really want to forbid the same parameters being used for other types of physics? Is this data structure forbidden from existing in the future? Do soft physics simulations need to reinvent this repo's parameters because the physics body extension was named rigid to discourage anyone from using it in a non-rigid context?

```json
{
	"name": "FlagWhichMayWaveIfSoftIsSupportedOtherwiseItIsStiffAndPivotsAroundThePole",
	"extensions": {
		"KHR_physics_body": {
			"motion": {
				"mass": 7,
				"linearVelocity": [1, 2, 3]
			},
			"joint": { ... }
		},
		"KHR_physics_soft": { ... }
	}
}
```

**Comment by antpb** [comment]
After some discussions with folks familiar with the decision I understand more that the decision was made to go with the existing naming. closing
