### ISSUE TITLE
Forces

### ISSUE THREAD

**Issue by Shinmera** [eoineoineoin/glTF_Physics#25]
It is quite odd to me that the spec includes a ``gravityFactor`` field, but no description for what forces should even be active in the scene to begin with, or what their parameters are supposed to be.

I think the field should either be removed, or a way to specify forces should be added. This could also be extended to make the trigger volumes carry some innate behaviour, such as activating certain forces for objects touching the trigger volume. As it stands right now, trigger volumes are entirely application-specified.

If forces are added, naturally the set of required force types and how they apply to objects must be specified as well, which sounds rather tricky to work out.

**Comment by eoineoineoin** [comment]
Simulations will typically expose a global "acceleration due to gravity" - i.e. gravity isn't _really_ a force, as the acceleration is independent of the body mass.  Without an additional factor to control this, mathematically, a body with infinite mass would still fall down due to gravity; the sample at https://eoineoineoin.github.io/glTF_Physics_Babylon/packages/demo/dist/#sceneIndex=5 uses a few different gravity factors - the balloons have a negative gravity factor, while the blue wheel has zero, allowing it to remain in-place. While not physically accurate, it is a useful parameter to be able to configure on a body. 

While the idea of exposing a generic interface for forces, is nice, I think the parameterization would be very complex. There's an enormous variety of _what_ forces you might want and how they're calculated. In my experience, simulations don't typically have a "native" force interface and instead, developers build those as additional components.

**Comment by Shinmera** [comment]
Then I think the spec should still specify some default value for what that acceleration is, otherwise simulations will vary wildly between different viewers due to differing default gravity acceleration factors.

**Comment by eoineoineoin** [comment]
I get where you're coming from; a (much!) earlier version of the spec did include a field to specify a gravity per-document, but this was removed based on feedback. The rationale was that the application is typically going to determine the global gravity and allowing an individual scene to specify it could lead to problematic cases where two glTF scenes with different gravity directions were loaded into the same scene.

I think the behaviour of different viewers having different results _is_ desirable. In most cases, I'd expect that an application is going to use "Earth gravity;" however, suppose we had an application which was using "moon gravity" - in this kind of scenario, you wouldn't want the loaded assets to be using Earth-scale gravity.

**Comment by Shinmera** [comment]
Well yes, that's why I said a default, rather than a strictly specified mandate. I imagine for many situations it's better to have some reference value that can be used to compare test cases and ensure proper implementations. Cases as you've described with specific requirements for gravity or whatever can simply do what they need, instead.

**Comment by eoineoineoin** [comment]
Closing as "not-planned" - if necessary, future extensions could add different kind of force fields.
