### ISSUE TITLE
Require colliders to be direct children of bodies, not indirect children

### ISSUE THREAD

**Issue by aaronfranke** [eoineoineoin/glTF_Physics#9]
The draft spec README currently has this text:

> ### Rigid Bodies
> 
> All descendant nodes should move with that node - i.e. the physics engine should treat them as part of a single rigid body.
> 
> ### Colliders
> 
> If the node is part of a rigid body (i.e. itself or an ascendent has `rigidBody` properties) then the collider belongs to that rigid body and should move with it during simulation.

I don't disagree with this logic in principle, but colliders being indirect descendants, such as grandchildren, is not a supported feature in Godot Engine, so it's not portable to there.

In Godot Engine, a collider that is not a direct child is not a part of the body. This allows for things like having another body as a child of a body and not having that child body's collider children be a part of the parent body's colliders. This is often used for triggers like a car's headlights (which I know MSFT physics has another approach for, but to be clear, I'm only bringing it up as an explanation for why this change helps with portability in Godot).

I propose that instead we require colliders be direct children of their body to enhance compatibility with Godot Engine.

**Comment by eoineoineoin** [comment]
My concern with this suggestion is that it puts an additional burden on how you lay out your scenes. Content _do_ construct objects in hierarchies (both as a way to organize their scene and so that you can move a bunch of nodes by modifying a single parent node) so it feels a little strange for me to say "that way you were doing things before - that doesn't work if you use this extension."

As for the Godot support, I've actually been experimenting with a Godot importer - it's _really_ rough-and-ready, right now, but I've made it public so that you can see it. I did encounter this problem, but it had a [trival workaround](https://github.com/eoineoineoin/glTF_Physics_Godot_Importer/blob/main/addons/MSFT_Physics_Importer/MSFT_CollisionShape.gd) so I don't think there's a _technical_ reason that the Godot collision node _needs_ to be an immediate child.

**Comment by aaronfranke** [comment]
Sure, that work-around does work, but since it makes a new node type it doesn't have feature parity with the built-in CollisionShape3D, and it goes contrary to the expectations of Godot users. It may be a better work-around to have the importer create the built-in collision shape node as a child of the body.

Out of the issues I've opened so far, I feel the least strong about this one. If we want to allow this, some users may find it useful, and it's definitely something that can be worked around, but I just want you to be aware that this is one additional thing that can hinder the portability of this standard between game engines.
